app:
  baseUrl: http://localhost:7000

backend:
  baseUrl: http://localhost:7000
  listen:
    port:
      $env: PORT

auth:
  environment: production
  providers:
    github:
      production:
        clientId:
          $env: GITHUB_PRODUCTION_CLIENT_ID
        clientSecret:
          $env: GITHUB_PRODUCTION_CLIENT_SECRET

techdocs:
  requestUrl: https://demo.backstage.io/api/techdocs
  storageUrl: https://demo.backstage.io/api/techdocs/static/docs
  builder: 'external'
  generators:
    techdocs: local
  publisher:
    type: 'local'
    googleGcs:
      credentials:
        $env: TECHDOCS_GCS_CREDENTIALS
      projectId:
        $env: TECHDOCS_GCS_PROJECT_ID
      bucketName:
        $env: TECHDOCS_GCS_BUCKET
